### ISSUE TITLE
Not able to download the skin type and acne model 

### ISSUE THREAD

**Issue by Gk15200-Aug** [tamjid1108/skin#1]
i am facing the issue while downloading the model

PS C:\Users\Guru Kiran\Downloads\Skin detection\skin> git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/tamjid1108/skin.git/info/lfs'

so can you share the model it will help for me to run the model

**Comment by tamjid1108** [comment]
Added the drive link to trained models to readme.md. Feel free to use them
